// main.go
package main

import (
	"SimpleWeb/api"
	_ "SimpleWeb/docs" // docs is generated by Swag CLI
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"log"
)

func main() {

	// Create a new Gin router
	router := gin.Default()

	// Swagger documentation route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// api routes
	v1 := router.Group("/api/v1")
	{
		v1.GET("/ping", api.Ping)                   // removed trailing slash
		v1.GET("/user/:id", api.GetUser)            // already correct
		v1.GET("/launchProcess", api.LaunchProcess) // removed trailing slash
		v1.GET("/resetDatabase", api.ResetDatabase) // removed trailing slash and fixed case
		v1.GET("/top-devices", api.TopDevices)      // removed trailing slash and fixed case
	}

	// Start the server
	err := router.Run(":8080")
	if err != nil {
		log.Fatal(err)
	}
}
